const jcat=[
    {
    index:0,
    image:"../images/google.png",
    title:"Web Developer",
    rate:"$900-1200/m",
    av:"Full Time",
    companyname:"Google",
    location:"USA",
    vacancy:"03",
    hours:"50hours / Week",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    workplace:"Work from home",
    education:"Bachelor degree in any Computer Science Course.",
    experience:"2 to 5 years",

},
    {
        index:1,
        image:"../images/uber.png",
        title:"Freelancer",
        rate:"$1000-1200/m",
        av:"Freelancer",
        companyname:"Uber",
    location:"USA",
    vacancy:"03",
    hours:"50hours / Week",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    workplace:"Work from home",
    education:"Bachelor degree in any Computer Science Course.",
    experience:"2 to 5 years",
    },

    {
        index:2,
        image:"../images/linkedin.png",
        title:"Bussiness Associate",
        rate:"$1000-1200/m",
        av:"Part Time",
        companyname:"linkedin",
    location:"USA",
    vacancy:"03",
    hours:"50hours / Week",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    workplace:"Work from home",
    education:"Bachelor degree in any Computer Science Course.",
    experience:"2 to 5 years",
    },

    {
        index:3,
        image:"../images/facebook.png",
        title:"Digital Marketing",
        rate:"$1000-1200/m",
        av:"Full Time",
        companyname:"facebook",
    location:"USA",
    vacancy:"03",
    hours:"50hours / Week",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    workplace:"Work from home",
    education:"Bachelor degree in any Computer Science Course.",
    experience:"2 to 5 years",
    },

    {
        index:4,
        image:"../images/yahoo.png",
        title:"User Experience",
        rate:"$1000-1200/m",
        av:"Part Time",
        companyname:"yahoo",
    location:"USA",
    vacancy:"03",
    hours:"50hours / Week",
    description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    workplace:"Work from home",
    education:"Bachelor degree in any Computer Science Course.",
    experience:"2 to 5 years",
    },

    
]